defmodule Hostctl.Statistics do
  @moduledoc "Private domain traffic reports generated by GoAccess."
  alias Hostctl.Accounts.Scope
  alias Hostctl.Hosting
  alias Hostctl.Repo
  import Ecto.Query

  def config, do: Application.get_env(:hostctl, __MODULE__, [])
  def root, do: Keyword.get(config(), :root, "/var/lib/hostctl/statistics")
  def available?, do: System.find_executable(Keyword.get(config(), :goaccess, "goaccess")) != nil

  def domain!(%Scope{user: %{role: "admin"}}, id), do: Hosting.get_domain_for_admin!(id)
  def domain!(%Scope{} = scope, id), do: Hosting.get_domain!(scope, id)

  def snapshot(scope, id, kind \\ "live") when kind in ["live", "history"] do
    domain = domain!(scope, id)
    live = manifest(domain.id, "live")
    history = manifest(domain.id, "history")

    %{
      domain: domain,
      live: live,
      history: history,
      overview: overview(domain.id, if(kind == "history", do: history, else: live)),
      available?: available?()
    }
  end

  def refresh(scope, id) do
    domain = domain!(scope, id)

    if domain.statistics_enabled do
      collect_domain(domain)
    else
      {:error, "Automatic collection is disabled for this domain. Enable it to collect traffic."}
    end
  end

  def set_enabled(scope, id, enabled) when is_boolean(enabled) do
    domain!(scope, id)
    |> Ecto.Changeset.change(statistics_enabled: enabled)
    |> Repo.update()
  end

  defp collect_domain(domain) do
    subs = Hosting.list_subdomains(domain) |> Enum.map(& &1.name)

    s3_subs =
      Hosting.list_s3_backends(domain)
      |> Enum.map(& &1.subdomain)
      |> Enum.reject(&(&1 in [nil, ""]))

    hosts = [domain.name | Enum.map(Enum.uniq(subs ++ s3_subs), &(&1 <> "." <> domain.name))]

    run(
      "collect",
      domain.id,
      ["--log-root", Keyword.get(config(), :log_root, "/var/log/nginx")] ++
        Enum.flat_map(hosts, &["--host", &1])
    )
  end

  def import_history(scope, id, source) do
    domain = domain!(scope, id)
    run("history", domain.id, ["--source", source])
  end

  def enabled_ids do
    Repo.all(from d in Hosting.Domain, where: d.statistics_enabled, select: d.id, order_by: d.id)
  end

  def read_report(scope, id, kind, archive_id \\ nil)

  def read_report(scope, id, kind, archive_id) when kind in ["live", "history"] do
    domain = domain!(scope, id)

    with %{} = data <- manifest(domain.id, kind),
         {:ok, relative, type} <- report_entry(data, archive_id),
         path <- Path.join([root(), to_string(domain.id), data["generation"], relative]),
         :ok <- regular_path(path),
         {:ok, stat} <- File.stat(path),
         true <- stat.size <= 32 * 1024 * 1024,
         {:ok, body} <- File.read(path) do
      {:ok, body, type}
    else
      _ -> {:error, :not_found}
    end
  end

  def read_report(_scope, _id, _kind, _archive_id), do: {:error, :not_found}

  defp report_entry(_data, nil), do: {:ok, "report.html", :goaccess}

  defp report_entry(data, archive_id) when is_binary(archive_id) do
    if String.match?(archive_id, ~r/\A[a-f0-9]{64}\z/) do
      case Enum.find(data["reports"] || [], &(&1["id"] == archive_id)) do
        nil ->
          {:error, :not_found}

        report ->
          {:ok, "archive/" <> archive_id,
           if(report["html"], do: :archive_html, else: :archive_text)}
      end
    else
      {:error, :not_found}
    end
  end

  defp manifest(id, kind) do
    path = Path.join([root(), to_string(id), kind <> ".json"])

    with :ok <- regular_path(path),
         {:ok, json} <- File.read(path),
         {:ok, data} <- Jason.decode(json),
         generation when is_binary(generation) <- data["generation"],
         true <- String.match?(generation, ~r/\Ag-[a-f0-9]{32}\z/) do
      data
    else
      _ -> nil
    end
  end

  defp overview(id, %{"generation" => generation}) do
    path = Path.join([root(), to_string(id), generation, "report.json"])

    with :ok <- regular_path(path),
         {:ok, stat} <- File.stat(path),
         true <- stat.size <= 32 * 1024 * 1024,
         {:ok, body} <- File.read(path),
         {:ok, report} when is_map(report) <- Jason.decode(body) do
      %{pages: top_rows(report, "requests"), sources: top_rows(report, "referring_sites")}
    else
      _ -> nil
    end
  end

  defp overview(_id, _manifest), do: nil

  defp top_rows(report, key) do
    rows =
      case report[key] do
        %{"data" => rows} when is_list(rows) -> rows
        _ -> []
      end

    rows =
      rows
      |> Enum.flat_map(fn
        %{"data" => label, "hits" => %{"count" => hits}} = row
        when is_binary(label) and is_integer(hits) and hits >= 0 ->
          method =
            if key == "requests" and is_binary(row["method"]), do: row["method"] <> " ", else: ""

          [%{label: String.slice(method <> label, 0, 512), hits: hits}]

        _ ->
          []
      end)
      |> Enum.sort_by(& &1.hits, :desc)
      |> Enum.take(5)

    maximum = Enum.reduce(rows, 1, &max(&1.hits, &2))

    rows
    |> Enum.with_index(1)
    |> Enum.map(fn {row, rank} ->
      Map.merge(row, %{id: rank, width: round(row.hits / maximum * 100)})
    end)
  end

  defp regular_path(path) do
    case File.lstat(path) do
      {:ok, %{type: :regular}} -> safe_parents(Path.dirname(path))
      _ -> {:error, :unsafe_path}
    end
  end

  defp safe_parents("/"), do: :ok

  defp safe_parents(path) do
    case File.lstat(path) do
      {:ok, %{type: :directory}} -> safe_parents(Path.dirname(path))
      _ -> {:error, :unsafe_path}
    end
  end

  defp run(action, id, options) do
    helper = Application.app_dir(:hostctl, "priv/statistics/collect.py")

    args =
      [
        helper,
        action,
        "--root",
        root(),
        "--domain-id",
        to_string(id),
        "--goaccess",
        Keyword.get(config(), :goaccess, "goaccess")
      ] ++ options

    args =
      case Keyword.get(config(), :geoip_database) do
        nil -> args
        path -> args ++ ["--geoip", path]
      end

    runner = Keyword.get(config(), :runner, &System.cmd/3)

    case runner.(Keyword.get(config(), :python, "python3"), args, stderr_to_stdout: true) do
      {output, 0} ->
        case Jason.decode(output) do
          {:ok, result} ->
            {:ok, result}

          _ ->
            {:error,
             "Statistics returned an invalid report. The previous report is still available."}
        end

      {output, _} ->
        case Jason.decode(output) do
          {:ok, %{"error" => reason}} -> {:error, reason}
          _ -> {:error, "Statistics collection failed. The previous report is still available."}
        end
    end
  rescue
    ErlangError ->
      {:error, "Install GoAccess from Administration → Features before collecting statistics."}
  end
end
